### ISSUE TITLE
Easypost.Shipment.options

### ISSUE THREAD

**Issue by jmalatia** [EasyPost/easypost-csharp#10]
Is there a reason why Shipment.options doesn't have a class model?  Can one be added?

**Comment by att14** [comment]
I was going to do this, but then I realized that we are constantly adding options and I don't want this library to get too far out of sync or for people to be required to update their client if they want the new features. Going to leave this as a `Dictionary`. Sorry about that. You can see a list of options [here](https://www.easypost.com/docs/api#shipping-options).
