### ISSUE TITLE
Add support for purchasing insurance at same time as label

### ISSUE THREAD

**Issue by eprussell** [EasyPost/easypost-csharp#105]
Currently appears that the required steps are to first create and purchase the shipment, then subsequently add insurance.  

[Documentation](https://www.easypost.com/docs/api/csharp.html#buy-a-shipment) indicates that this should be possible all at once, and it is with other libraries, but not this one.

**Comment by chadwixk** [comment]
This causes you to have to do 2 calls...one to buy and then a separate to insure the shipment. So this adds application response time to the user experience while waiting to buy and print a label, as well as adds extra overhead to the EasyPost servers. 

Hoping for a fix soon.
