### ISSUE TITLE
Zip code validation does not seem to be working with dotNet lib 4.5 (v 2.3.1.4)

### ISSUE THREAD

**Issue by ameetj85** [EasyPost/easypost-csharp#111]
Hello folks,

I am using the dotNet 4.5 version of the library. I have set verify_strict to "delivery" and "zip4", even though my zipcode is only 5 characters long. When I call .Create() on the Address object I am able to verify that the library correctly identifies wrong or missing street address values and city and state values. I am unable to get the library to verify the zipcode. I can use almost any 5 digit zipcode and the Create() method raises no errors.

Please advise.
Thanks.
Ameet.

The following is the address that I am using:
name=John Doe
street1=3 Park Ave
street2=22nd Floor
city=New York
state=NY
zip=77777 <--- this should be raised as an invalid zipcode value.
country=US

Following is the code that I am using in my test app:

toAddress = new Address()
                        {
                            company = values[0],
                            street1 = values[1],
                            street2 = values[2],
                            city = values[3],
                            state = values[4],
                            country = values[5],
                            zip = values[6],
                            residential = false,
                            verify_strict = new List<string>() { "delivery", "zip4" }
                            
                        };
try
                {
                    toAddress.Create();
                }
                catch(HttpException ex)
                {
                    Console.WriteLine("Recepient Address verification failed: " + ex.Message);
                }

**Comment by ameetj85** [comment]
[EasyPost_RatesTest.zip](https://github.com/EasyPost/easypost-csharp/files/1933483/EasyPost_RatesTest.zip)
Code attached

**Comment by att14** [comment]
Its most likely not raising because its actually correcting the zipcode of the address you passed. If we are able to correct an address an error is not raised. If you email support@easypost.com we would be happy to look into the exact request you are making.
