### ISSUE TITLE
Not able to create a Pickup for a given shipment.

### ISSUE THREAD

**Issue by sasanka1983** [EasyPost/easypost-csharp#116]
Hello,

I am not able to create a Pickup request for a shipment. I am getting "PICKUP.BATCH_CARRIER.INCONSISTENT" error.  

Also, For any from address (US Address), it is returning USPS carrier rates for both Production or Test. Am i missing something? Please help.

Below is the code snippet

 var parcel = new Parcel()
            {
                length = parcelDimensions.Length,
                width = parcelDimensions.Width,
                weight = parcelDimensions.Weight,
                height = parcelDimensions.Height
            };
            var shipment = new Shipment()
            {
                from_address = easyPost_fromAddr,
                to_address = easyPost_toAddr,
                parcel = parcel,
            };

            try
            {
                shipment.Create();

            }

 var pickupParams = new Dictionary<string, object>()
            {
                {"address", easyPost_fromAddr},
                {"shipment", batchshipment},
                {"min_datetime", minShippingDate},
                {"max_datetime", maxShippingDate},
                {"is_account_address",false },
                {"instructions","this is a test" },
                {"reference","Eurofins" }
            };
            try
            {
                var pickupRequest = Pickup.Create(pickupParams);
               
            }

Thanks,
Sasanka

**Comment by att14** [comment]
The shipment must be purchased in order to create a Pickup otherwise we don't know which carrier you want us to schedule the pickup with. If you don't want to purchase the shipments before creating a Pickup you must use a Batch and specify the carrier and service level for each Shipment.
