### ISSUE TITLE
Version 2.4.0 throwing dependency issues realted to Newtonsoft.Json and RestSharpSigned on .NET Core 2.0 Project

### ISSUE THREAD

**Issue by kgrvr** [EasyPost/easypost-csharp#119]
![img_31082018_120948_0](https://user-images.githubusercontent.com/11766028/44896801-2156f480-ad17-11e8-9159-a63ccedcf3f9.png)

Adding dependency to .NET Core 2.0 project throws the above mentioned warning. Newtonsoft.Json requires version 11, which is thrown at runtime, and RestSharp package is not compatible with .NET Core 2.0.
Please help me resolve this issue.

**Comment by att14** [comment]
I will be releasing a new version shortly. Please try it and let me know if that fixes your problem.

**Comment by jmalatia** [comment]
@att14  Please remove the reference to RestSharpSigned in netcoreapp2.0 project and add reference to RestSharp instead which is .net core compatible.  RestSharp is now signed and RestSharpSigned is obsolete, see [https://github.com/restsharp/RestSharp#note-on-restsharpsigned](url).

Additionally make corrections to other projects that no longer need to reference RestSharpSigned.  You will also need to correct .nuspec and other similar supporting files.

Easypost.nuspec file:
In the `<files>` section there is no reference to netcoreapp20, so you will need to add

```
    <file src="lib\netcoreapp2.0\EasyPost.netcoreapp20.dll" target="lib\netcoreapp2.0" />
    <file src="lib\netcoreapp2.0\netcoreapp20.xml" target="lib\netcoreapp2.0" />
```

Please note in the .nuspec file the directory name has a period in it, `netcore2.0` and the project name has no periods... just an FYI as it was confusing me for a little bit.

Additionally in the folder `lib\netcoreapp2.0`, there are other files in there named `easypost.NetCore.*` (without the 20), not sure what purpose those have in their... maybe from a first try?

**Comment by att14** [comment]
@jmalatia, you are right. Try the new 2.5.0.1 version. I did not remove `RestSharpSigned` from .Net 3.0 and .Net 3.5 because the new version of `RestSharp` isn't available for those versions.
