### ISSUE TITLE
Support for ASP.Net Standard Version 4.6.x

### ISSUE THREAD

**Issue by nesterenes** [EasyPost/easypost-csharp#122]
Per issue #50 , This library doesn't currently support 4.6.x. The lack of support for that version prevents NuGet package updates because of conflicts between applications using `RestSharpSigned` and `RestSharp`. If `RestSharpSigned` is installed, easypost-csharp latest library cannot be used on ASP.Net version 4.6.x. However the library is functional on ASP.Net 4.6.x with previous easypost-csharp version 2.3.1.4.

https://github.com/EasyPost/easypost-csharp/issues/50

Requesting support for version 4.6.x with `RestSharpSigned` usage instead of `RestSharp`.

![image](https://user-images.githubusercontent.com/1128121/46629629-8c15ff80-cb0f-11e8-998c-5eaa7a846c99.png)

**Comment by jmalatia** [comment]
RestSharpSigned is obsolete per [https://github.com/restsharp/RestSharp](https://github.com/restsharp/RestSharp) ([last version was 8/2015](https://www.nuget.org/packages/RestSharpSigned/)) as RestSharp is now signed.

**Comment by Justintime50** [comment]
We don't plan to do this per the previous comment. `RestSharpSigned` is now 6 years outdated and as such, `RestSharp` should be used instead.
