### ISSUE TITLE
Multiple EasyPost API keys don't work with latest version 2.5.1

### ISSUE THREAD

**Issue by taivt0109** [EasyPost/easypost-csharp#125]
If you are operating with multiple EasyPost API keys, or wish to delegate the construction of the client requests, configure the ClientManager with a delegate at application initialization.

using EasyPost;

ClientManager.SetCurrent(() => new Client(new ClientConfiguration("yourApiKeyHere")));

I reference this document. But it doesn't work with version 2.5.1

i got an error " 'Client' does not contain a constructor that takes 1 arguments "

**Comment by att14** [comment]
I have two tests that should cover this exact situation. https://github.com/EasyPost/easypost-csharp/blob/master/EasyPostTest/ClientManagerTest.cs#L30-L44'

Do you have a more specific example or some modification to the existing tests that would reproduce this behavior?

**Comment by nicknasirpour** [comment]
Hi, I am having the same issue accessing this constructor.

The Client constructor in reference has an "internal" access modifier, which is why you are able to use it within your EasyPostTest project... it is within the same solution/assembly... But we are unable to use it in our solutions. It should be marked as public if you would like us to use to have access.

**Comment by nicknasirpour** [comment]
Here is the commit where the access modifier is changed from public to internal:

https://github.com/EasyPost/easypost-csharp/pull/100/commits/2f8cb663998e93902f0c50303900bd2b3de6b287

**Comment by Justintime50** [comment]
The constructor was corrected in #158. It should also be noted that the way in which this library is written does not allow for thread-safe multi-API key usage (see #98). We are considering a refactor that may allow for this; however, it won't be in the immediate future.

**Comment by nwithan8** [comment]
As of [v4.0.0](https://github.com/EasyPost/easypost-csharp/releases/tag/v4.0.0), this library is instance-based and considered thread-safe.
