### ISSUE TITLE
User Create method missing on User object

### ISSUE THREAD

**Issue by drakinfar** [EasyPost/easypost-csharp#127]
when trying to create a child user as set out in the documentation the Create method is missing

code

```csharp
using EasyPost;
EasyPost.ClientManager.SetCurrent("<YOUR_PRODUCTION_API_KEY>");

User user = new User() { name = "Child Account Name" };

user.Create();
```

user.Create() is missing from the user object.

this is on version 2.5.1 of the nuget package.

**Comment by drakinfar** [comment]
there is a static member that allows fro creates but the documentation shows a non-static example. Assuming the documentation needs to be updated.

**Comment by Justintime50** [comment]
The [documentation](https://www.easypost.com/docs/api/csharp#child-users-create-codesample) and [library](https://github.com/EasyPost/easypost-csharp/blame/master/EasyPost/User.cs#L45-L59) appear to match and have for some years, you can call `user.Create()` to create a child user. Closing this, if I've misunderstood the request, feel free to reopen with additional details.
