### ISSUE TITLE
Add Support to Register FedEx Accounts

### ISSUE THREAD

**Issue by Volnyxxe** [EasyPost/easypost-csharp#130]
EasyPost has recently added a new endpoint to allow developers to register their FedEx accounts. It would be nice if this was available in the C# library.

From an EasyPost support ticket:
It is possible to add FedEx via an API call and I have an example cURL you can use as a template:

curl -X POST https://api.easypost.com/v2/carrier_accounts/register \
 -u <CHILD_PRODUCTION_API_KEY>: \
 -d 'carrier_account[type]=FedexAccount' \
 -d 'carrier_account[description]=My FedEx Account' \
 -d 'carrier_account[reference]=my-reference' \
 -d 'carrier_account[registration_data][account_number]=123456789' \
 -d 'carrier_account[registration_data][shipping_streets]=123 Main Street' \
 -d 'carrier_account[registration_data][shipping_city]=San Francisco' \
 -d 'carrier_account[registration_data][shipping_state]=CA' \
 -d 'carrier_account[registration_data][shipping_postal_code]=94104' \
 -d 'carrier_account[registration_data][shipping_country_code]=US' \
 -d 'carrier_account[registration_data][corporate_first_name]=John' \
 -d 'carrier_account[registration_data][corporate_last_name]=Doe' \
 -d 'carrier_account[registration_data][corporate_job_title]=CEO' \
 -d 'carrier_account[registration_data][corporate_company_name]=Acme Inc' \
 -d 'carrier_account[registration_data][corporate_phone_number]=415-123-4567' \
 -d 'carrier_account[registration_data][corporate_email_address]=jdoe@example.com' \
 -d 'carrier_account[registration_data][corporate_streets]=1 Montgomery Street, 4th Floor' \
 -d 'carrier_account[registration_data][corporate_city]=San Francisco' \
 -d 'carrier_account[registration_data][corporate_state]=CA' \
 -d 'carrier_account[registration_data][corporate_postal_code]=94104' \
 -d 'carrier_account[registration_data][corporate_country_code]=US'
**NOTE** Make sure the leave the colon after the API key in the cURL.

**Comment by Justintime50** [comment]
We definitely want to incorporate this to the client libraries. Thanks for submitting this issue! We are taking a holistic view so that we can allow registration of more than just FedEx accounts via a single method/interface (UPS in addition for instance). We don't yet have an ETA but it's something we want to add in the future.

**Comment by Justintime50** [comment]
Hey @Volnyxxe, adding a CSP enabled FedEx account via API call is now supported. Please reach out to support@easypost.com for additional details on getting this setup (you should even be able to use the client library to do it.)
