### ISSUE TITLE
VB.Net error Create is ambiguous

### ISSUE THREAD

**Issue by chargerback-ron** [EasyPost/easypost-csharp#151]
I'm using VB.Net to develop an EasyPost solution using the EasyPost.Net35.dll. When compiling I get the following error:

> error BC31429: 'Create' is ambiguous because multiple kinds of members with this name exist in class 'EasyPost.Address'.

According to documentation on MSDN, this error means that the source for the DLL was written in C#, which is case sensitive, so create and Create are two different things, whereas VB is case insensitive, so create and Create are the same thing. I looked through the code in this repo and I don't see a case difference in Address for Create. However, this repo seems to be pretty old; it says last updated 2014?

**Comment by Justintime50** [comment]
Hey @chargerback-ron, we have released newer versions since that are not reflected on this GitHub page (see: https://www.nuget.org/packages/EasyPost-Official/).

As for your question, I can try digging around. Maybe @roehnan can shed some light on this?

**Comment by chargerback-ron** [comment]
Thank you @Justintime50 I have verified that I am in fact using the latest version of the DLL from NuGet.

**Comment by chargerback-ron** [comment]
@Justintime50 any update on my issue? I'm stalled in my EasyPost implementation right now. Thank you!

**Comment by Justintime50** [comment]
I'll be honest, C# isn't my forte; however, in my research, I found the following that may be useful. I'm not entirely sure if this is an issue with the C# client library or the way it's being implemented on your side. Can you share a code snippet or gist here that we can take a look at?

Useful links (assuming this is a problem with the implementation of this library and not the actual library itself):

- https://visualstudiomagazine.com/articles/2016/06/01/conflicts-in-c-and-visual-basic.aspx
-  https://stackoverflow.com/questions/3491801/vb-net-ambiguous-class-name-error-when-no-ambiguity-exists/3660954#3660954

Let me know if either of these help or you are able to share a bit more context that we can look at. Thanks!

**Comment by chargerback-ron** [comment]
Be happy to! It's quite easy to reproduce the error. Just try to compile this and you will get the error on the line FromAddress.Create(). It's definitely an error with the client library. The DLL is marked as "Language Neutral" but it is not if this simple code cannot compile. The Reflection link you sent looks promising; I'll let you know if it works.

        Dim FromAddress As New Address

        FromAddress.name = ShipperContact
        FromAddress.company = ShipperName
        FromAddress.street1 = ShipperAddress
        FromAddress.street2 = ShipperAddress2
        FromAddress.city = ShipperCity
        FromAddress.state = ShipperState
        FromAddress.zip = ShipperPostalCode
        FromAddress.phone = ShipperPhone
        FromAddress.country = ShipperCountry

        Try
            FromAddress.Create()
        Catch ex As EasyPost.HttpException
            Dim strError As String = String.Format("EasyPostRate error {0} creating from address = {1}", ex.Code, ex.Message)
            File.AppendAllText(LogFile, strError)
            strHTML = String.Format("0|0|{0}", strError)
            Response.Write(strHTML)
            Response.End()
        End Try

        Shipment.from_address = FromAddress

**Comment by nwithan8** [comment]
> I'm using VB.Net to develop an EasyPost solution using the EasyPost.Net35.dll. When compiling I get the following error:
> 
> > error BC31429: 'Create' is ambiguous because multiple kinds of members with this name exist in class 'EasyPost.Address'.
> 
> According to documentation on MSDN, this error means that the source for the DLL was written in C#, which is case sensitive, so create and Create are two different things, whereas VB is case insensitive, so create and Create are the same thing. I looked through the code in this repo and I don't see a case difference in Address for Create. However, this repo seems to be pretty old; it says last updated 2014?

@chargerback-ron I think Visual Basic is getting caught up because there is a static `Create` method (i.e. `Address.Create(parameters)` and a non-static `Create` method (i.e. `myAddress.Create()`). Looking at your code snippet, you're trying to call the non-static one on the `FromAddress` object, but Visual Basic for some reason is still getting confused. I did some searching around, figuring it might be a quirk of the language (like the case-insensitivity) but couldn't find any conclusive answer about how Visual Basic handles static and non-static methods by the same name. Do you perhaps have any insight on that?

As for how we can address this, we are in discussions about potentially shifting away from our static methods altogether in favor of true instance-based OOP, which should alleviate the issue of the competing function names. I'll keep you updated as we know more.

**Comment by chargerback-ron** [comment]
@nwithan8 This [link](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/procedure-overloading) from MSDN specifies the rules for overloading functions in VB.Net. I suspect this may be the issue.

**Items Not Part of Signature**. You cannot overload a procedure without varying the signature. In particular, you cannot overload a procedure by varying only one or more of the following items:

- Procedure modifier keywords, such as Public, Shared, and Static

**Comment by nwithan8** [comment]
v3.0.0 is out with Visual Basic and F# compatibility.
