### ISSUE TITLE
Culture issue

### ISSUE THREAD

**Issue by nicknasirpour** [EasyPost/easypost-csharp#157]
Bonjour,

We are from Quebec and our systems have a French culture by default. 

Try adding and running this unit test:

```
[TestMethod]
public void TestBuyOrderFrThreadCulture()
{
    System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("fr");
    Order order = Order.Create(parameters);
    order.Buy("USPS", "Priority");

    Assert.IsNotNull(order.shipments[0].postage_label);
}

```
It will fail with a null reference. 
That is because the response data is null for some reason on this line: https://github.com/EasyPost/easypost-csharp/blob/1f4051a25beffa6432f471690e2047a186b7dbc0/EasyPost/Client.cs#L55

Our work around so far is to set the thread culture to English before interacting with the library:
           
```
System.Globalization.CultureInfo originalCulture = System.Threading.Thread.CurrentThread.CurrentCulture;
System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en");

```

and then we set it back afterwards

`System.Threading.Thread.CurrentThread.CurrentCulture = originalCulture;`

I'm hoping this provides a solution for some unresolved issues!

**Comment by nwithan8** [comment]
Thank you for reporting this, and apologies for the late reply.

Newer versions of our client library no longer use RestSharp's `response.Data` to deserialize JSON data, which, by extension, patches this issue.

If you have not already, we highly recommend upgrading to the latest version of this library.

I'm going to close this issue. Please report if this remains an issue.
