### ISSUE TITLE
Customs parameter for Shipment options

### ISSUE THREAD

**Issue by coryplowman** [EasyPost/easypost-csharp#177]
The options object does not contain the parameter

commercial_invoice_letterhead

which is required by certain countries in order to ship there.

**Comment by Justintime50** [comment]
We recently merged this into the master branch: https://github.com/EasyPost/easypost-csharp/blob/master/EasyPost/Options.cs#L83

You can either build from source for now or take advantage of the addition of this option when we release a new version of this client library. We are hoping to do so in the coming weeks.
