### ISSUE TITLE
Address CreateandVerify requires param

### ISSUE THREAD

**Issue by tig4647** [EasyPost/easypost-csharp#18]
When attempting to send in an object of Address to CreateAndVerify, service returns street missing. This only occurs when I only send in the AddressObject, if I send in the parameters as a dictionary the return is correct.

**Comment by att14** [comment]
`CreateAndVerify` is a static method. Calling it from the context of an instance doesn't make sense. If you would like to use `CreateAndVerify` you must pass a `Dictionary` to be created then verified. If you have an instance of an `Address` that has not been created, you can just use `Create`, then `Verify`.

**Comment by att14** [comment]
I am going to close this because I don't see any action item. If you still have questions feel free to reopen.

**Comment by tig4647** [comment]
I hadnt noticed it was static. I guess my point was it is typically better to have strong naming as opposed to dictionary. May I suggest changing CreateAndVerify?

**Comment by att14** [comment]
I'm not sure what you mean by strong naming. You can think of `CreateAndVerify` as an alternate constructor.
