### ISSUE TITLE
Tracker is missing many elements

### ISSUE THREAD

**Issue by tig4647** [EasyPost/easypost-csharp#19]
Within the tracker return there are many missing objects. For example: Tracking_Location, est_delivery_date,signed_by and others. Am I missing something obvious here?

**Comment by att14** [comment]
Will release a new version later today. I'll update this when that happens.

**Comment by tig4647** [comment]
I just finished adding the classes. Guess I should have waited.
Thank you!

**Comment by att14** [comment]
If you've modified your own library, feel free to submit a pull request.

**Comment by att14** [comment]
Released versions 1.1.4.1
