### ISSUE TITLE
NuGet says v.2.8.0, but downloaded dll is 2.5.1.3

### ISSUE THREAD

**Issue by chargerback-ron** [EasyPost/easypost-csharp#211]
I just tried downloading the 2.8.0 release from NuGet. Although 2.8.0 is the version NuGet reports it is installing, the dll is dated 11/2/2021 and when I look at properties, it still reports as 2.5.1.3. Additionally, there is still no Insurance object.

**Comment by jchen293** [comment]
@chargerback-ron 
Thanks for reporting this issue, can I know which version of .Net framework are you using?

**Comment by Justintime50** [comment]
Thanks for reporting this! We've identified an issue with our build/package process during releasing and will have another release out shortly to address this.

**Comment by Justintime50** [comment]
We have released `v2.8.1` that properly packages all the new changes from `v2.6.0` - `v2.8.0`. Thanks for your patience as we corrected this issue! We're actively improving our documentation and releasing process to ensure this is avoided in the future.

**Comment by chargerback-ron** [comment]
@Justintime50 Thank you for the fast turnaround.
