### ISSUE TITLE
Cannot use shipment.Create with a predefined package

### ISSUE THREAD

**Issue by nozzlegear** [EasyPost/easypost-csharp#26]
Maybe I've missed something, but right now the EasyPost API is returning an error when I try to call .Create() on an instance of a Shipment like so:

```
var shipment = new Shipment()
{
    to_address = ...,
    from_address = ...,
    parcel = new Parcel()
    {
        weight = 16,
        predefined_package = "UPSLetter"
    }
};

shipment.Create();
```

The error returned says "*Validation failed: Length is required when dimensions are supplied with parcel, Width is required when dimensions are supplied with parcel, Height is required when dimensions are supplied with parcel*". 

It's being raised because the client is sending `shipment[parcel][length]=0`, `shipment[parcel][width]=0` and `shipment[parcel][height]=0`, rather than allowing null values when a predefined package is present.

**Comment by att14** [comment]
This is fixed in version 1.2.0.0
