### ISSUE TITLE
Swap Update Brand, Carrier, User, and Webhook Endpoints to use PATCH HTTP Method

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easypost-csharp#272]
The `update brand`, `update carrier account`, `update user`, and `update webhook` endpoints/functions are supposed to use the `PATCH` HTTP method and not `PUT`. We should swap these endpoints in the lib from `PUT` to `PATCH`. As a part of this process, please re-record those four cassettes to ensure this continues to work.

**Comment by nwithan8** [comment]
> The `update user` and `update carrier account` endpoints/functions are supposed to use the `PATCH` HTTP method and not `PUT`. We should swap these endpoints in the lib from `PUT` to `PATCH`. As a part of this process, please re-record those two cassettes to ensure this continues to work

PUT is used in more than just those two places, per the screenshot below. Do we need to make the switch in these functions as well?
<img width="899" alt="image" src="https://user-images.githubusercontent.com/17054780/170152095-156f392d-5a38-4c04-aa84-c6223aaf0c2a.png">

**Comment by Justintime50** [comment]
Thanks for the callout @nwithan8, I'll check with other to see if we needed to update those too. EndShipper will definitely remain PUT, but webhooks and user brands may also switch.

**Comment by ryannguyen16** [comment]
I will look into this.

**Comment by Justintime50** [comment]
@nwithan8 per your callout and checking internally with stakeholders and additional testing, updating a webhook and updating a brand should also be PATCH and will be updated as a part of this process.
