### ISSUE TITLE
Add duty_payment object 

### ISSUE THREAD

**Issue by chadwixk** [EasyPost/easypost-csharp#315]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Add support in this library for the options > duty_payment object as referenced by EasyPost support:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/5115308/185248705-0d5a5f10-54cc-4ed2-8cdd-ffd6c8d5fead.png">

**Comment by nwithan8** [comment]
Thank you for your suggestion. The `duty_payment` option is not documented in our [public API docs](https://www.easypost.com/docs/api#options), but it appears this is a valid option. I will reach out to discuss updating our available options as needed.

**Comment by nwithan8** [comment]
A fix is underway and will be included in the next release of the library.

**Comment by chadwixk** [comment]
@nwithan8 great! Thank you. Any idea when the next release will be pushed out?

**Comment by nwithan8** [comment]
> @nwithan8 great! Thank you. Any idea when the next release will be pushed out?

Tomorrow, most likely.
