### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by issovuong** [EasyPost/easypost-csharp#32]
I want to use [Sourcegraph](https://sourcegraph.com) for easypost-csharp code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/EasyPost/easypost-csharp. (It should only take 30 seconds.)

Thank you!

**Comment by att14** [comment]
Sorry, C# is not supported with Sourcegraph.
