### ISSUE TITLE
DeliveredDutyPaid vs Incoterm?

### ISSUE THREAD

**Issue by chadwixk** [EasyPost/easypost-csharp#347]
Hello,

Just wondering how these play together. I'm assuming you originally had `DeliveredDutyPaid` (which is just one type of incoterm), then later expanded support for a full set of incoterms and added `incoterm`. `DeliveredDutyPaid` is also now not listed on the docs, so assuming it has been deprecated and replaced by incoterms? Is this correct?

We have programming logic around `DeliveryDutyPaid`, but now want to implement support for the full set of supported incoterms. I'm assuming instead of passing `DeliveryDutyPaid: true`, we can now pass `incoterm: DDP`.

What is the incoterm equivalent to pass in lieu of `DeliveryDutyPaid: false`? Leave it blank?

**Comment by Justintime50** [comment]
Hey @chadwixk,

You are correct, the current option is to send `"incoterm": "DDP"`. By leaving `incoterm` empty, you're essentially setting it to `false`.

For additional details on setting `incoterm`, you can search for it under [Shipment options](https://www.easypost.com/docs/api#options) on our docs or reach out to our awesome support team via support@easypost.com.
