### ISSUE TITLE
Add Ability to Register Carriers with Custom Flows

### ISSUE THREAD

**Issue by datelcry** [EasyPost/easypost-csharp#365]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Hello EasyPost team!

There is a request for a little but valuable improvement of CarrierAccountService.cs

The implementation of custom flows of registering carriers like Fedex/UPS requires us to write own code to reach your API endpoint despite the presence of official SDK
Your [article ](https://support.easypost.com/hc/en-us/articles/7469579510925-Adding-Carriers-with-Custom-Workflows) has the only example of curl request, but [CarrierAccountService](https://github.com/EasyPost/easypost-csharp/blob/master/EasyPost/Services/CarrierAccountService.cs) doesn't have /carrier_accounts/register endpoint.

So to avoid monitoring your API for updates of this endpoint in the future and for better experience of using the API I ask you to add the register endpoint into your API

Thanks in advance!

**Comment by TGKN** [comment]
Hi,
I'd like to second this request as I want to get rid of my custom code extensions for the easypost library.

**Comment by nwithan8** [comment]
> Hi,
> I'd like to second this request as I want to get rid of my custom code extensions for the easypost library.

This feature was added in https://github.com/EasyPost/easypost-csharp/pull/375 and will be included in the next release, currently scheduled for later this week.

**Comment by TGKN** [comment]
Hi,
I have switched to the version of the package in question and I am afraid it is not working as expected. Your code does abstract the different URLs that need to be called for FedEx and UPS but it does not take into consideration that I need to pass a differently structureed data. Instead of "credentials" I need to pass "registration_data". Everything else is the same. So if I still have to create a custom workflow for UPS and FedEx your fix did not really help me at all. Or am I missing something??
Greetz
Kai

**Comment by Justintime50** [comment]
@TGKN that is correct. Based on the `type` field of the create/update request, we'll route the request to the correct endpoint. You will however need to pass in the right set of parameters (`credentials` for most carriers, `registration_data` for FedEx/UPS). Updating as you have and using the functions as normal should work correctly. You can view the tests as an example as we have both flows listed there.

**Comment by nwithan8** [comment]
Hey @TGKN, just wanted to let you know that in v5.5.0, we've added custom parameter sets for FedEx and UPS (`CreateFedEx` and `CreateUps`) that will guide you through those unique parameter requirements.
