### ISSUE TITLE
Add equality overload for comparison of EasyPostObject and dictionary

### ISSUE THREAD

**Issue by nwithan8** [EasyPost/easypost-csharp#377]
Per https://github.com/nopSolutions/nopCommerce/issues/6424#issuecomment-1327729733

> Sorry you had to make custom extensions to compare a dictionary of parameters to an existing EasyPostObject (e.g. Parcel, Shipment). We have a first-party way of comparing two EasyPostObjects, but especially since we removed the first-party ToDictionary function, there's no built-in way to do that via our library. Perhaps we can reintroduce that.

**Comment by Justintime50** [comment]
Let's name this issue appropriately.
