### ISSUE TITLE
[Bug]: EasyPost.Models.API.Rate does not include the "rate" field

### ISSUE THREAD

**Issue by falconkirtaran** [EasyPost/easypost-csharp#399]
### Software Version

4.3.0

### Language Version

.NET 6

### Operating System

Windows

### What happened?

The rate object does not include the "rate" field indicated in the documentation, only ListRate and RetailRate.  This means I can't display the rate I'm actually going to pay for the shipment.

See https://www.easypost.com/docs/api#rates

### What was expected?

Please expose the negotiated rate field "rate".

**Comment by nwithan8** [comment]
Sorry, due to naming conflicts, the property you're looking for is `Price`.

**Comment by nwithan8** [comment]
For future reference, we have docs for this library specifically, available here: https://easypost.github.io/easypost-csharp/
