### ISSUE TITLE
Date Created/updated returns nothing 

### ISSUE THREAD

**Issue by tig4647** [EasyPost/easypost-csharp#40]
Prior to this recent update when an address was  created " date created" and "date updated" returns a date. Now they return nothing and it was not obvious that this became nullable.

**Comment by tig4647** [comment]
My bad, didnt notice it was nulalble. Was getting data before.

**Comment by att14** [comment]
Sorry, we we not returning this data correctly. We have fixed the issue. Thanks for reporting.
