### ISSUE TITLE
[Issue]: API not responding on any call

### ISSUE THREAD

**Issue by m-imran38** [EasyPost/easypost-csharp#404]
### Software Version

4.3.0

### Language Version

.NET Framework 4.8

### Operating System

Windows 11

### What happened?

1. I have upgraded the EasyPost API to the lates version 4.3.0and updated all the relevant integration.
2. My old version (2.5) in other project is working fine but in this version it is not responding on any API call.
3. I have tried creating address, shipment and getting the carrier accounts but there is no response.
4. For example:
`
string apiKey = System.Environment.GetEnvironmentVariable(API_Key_EP)!;
EasyPost.Client client = new EasyPost.Client(apiKey);
List<CarrierAccount> carrierAccounts = await client.CarrierAccount.All();
`
In the code above, the code "await client.CarrierAccount.All()" does not give any response
...
![image](https://user-images.githubusercontent.com/10240648/218060583-ebfb880f-c7b5-4956-88b7-d830cef88f3c.png)

### What was expected?

API call should give any response either success or error.

### Sample Code

```csharp
string apiKey = System.Environment.GetEnvironmentVariable(API_Key_EP)!;
EasyPost.Client client = new EasyPost.Client(apiKey);
List<CarrierAccount> carrierAccounts = await client.CarrierAccount.All();
```

**Comment by nwithan8** [comment]
Hello, thanks for reporting this!

To help us troubleshoot this, would you mind providing us with a bit more information:

- What platform are you running our library on? Is this, for example, an ASP.NET application, a backend system?
- What does the outer code that calls the code snippet you shared look like? Since the last version you used, 2.5, the library has made asynchronous, as denoted by the await keyword in front of each function call. Any outer method wrapping our library function calls [will also need to be asynchronous](https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#async-all-the-way) to execute properly.

Thanks in advance for helping us help you!

**Comment by m-imran38** [comment]
Hello, thanks for the response.


   - What platform are you running our library on? Is this, for example, an
   ASP.NET <http://asp.net/> application, a backend system?
   - What does the outer code that calls the code snippet you shared look
   like? Since the last version you used, 2.5, the library has made
   asynchronous, as denoted by the await keyword in front of each function
   call. Any outer method wrapping our library function calls will also
   need to be asynchronous
   <https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#async-all-the-way>
to
   execute properly.


This is an ASP .NET web application and MVC framework, i am calling the API
in a class and my method is async.
Following is the screenshot of the method.

[image: image.png]

I have called the API with and without the following line of code but same
result:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

If you need any further information then let me know, if there is some
specific configuration that i have missed then also help me regarding that.

Thanks

**Comment by nwithan8** [comment]
Sorry @m-imran38 , it looks like the image you tried to attach didn't get uploaded, would you mind sending it again?

**Comment by m-imran38** [comment]
The screenshot was inline, anyway i have attached it again.

[image: image.png]

**Comment by nwithan8** [comment]
@m-imran38 It doesn't seem like GitHub automatically adds photos when responding via email, you might have to respond on the GitHub page directly for the attachment to work.

**Comment by m-imran38** [comment]
![image](https://user-images.githubusercontent.com/10240648/218655942-ba8fd0a8-c2bc-47ec-bf96-d8c5692cb7d4.png)

**Comment by nwithan8** [comment]
@m-imran38 Thank you for the image. Personally, nothing is immediately jumping out to me as an issue, but if you wouldn’t mind, could you confirm a few things for us to help us debug?

1. Is your API key being set and passed into the client properly? It seems like you are using a static key name, and pulling the API key from the environment by that key name. When an API call is being made, the API should throw an unauthorized exception if the API key provided is invalid. If that’s the case, in the code snippet you shared, the API error may have triggered the "catch" clause?
2. Did an API call occur? Is there a way to see if an actual HTTP request was attempted by the EasyPost client, perhaps in your logs somewhere, or via a debugging session?

Thank you again for helping us figure this out.

**Comment by m-imran38** [comment]
![Screenshot 2023-02-17 102101](https://user-images.githubusercontent.com/10240648/219560233-d03b1613-cd7c-4b30-acae-d23305c01338.png)
Yes, the API key is passed as you can see in the screenshot, and whichever method I called there is no exception and no response.

**Comment by m-imran38** [comment]
https://user-images.githubusercontent.com/10240648/219566830-b6ede7b9-1061-40ba-a426-8a0cf074d096.mp4

here is the debug session of the api call.

**Comment by m-imran38** [comment]
Thank you for your help I am able to figure out the issue and able to fix it and it is working now.
This was the issue: "Is it being called as await sync_shipment_accounts(storeId)".

**Comment by nwithan8** [comment]
Glad we could figure it out!
