### ISSUE TITLE
Support for Latest C# and Asp.Net (DotNetCore)

### ISSUE THREAD

**Issue by NVentimiglia** [EasyPost/easypost-csharp#49]
Currently, this package does not work with the most current version of DotNet and C#. DotNetCore, the latest version of C# and Asp.Net has been out for over a month. Please support it.

**Comment by att14** [comment]
I've been meaning to make a few changes to the structure of the repository and this will fit into that. Will you be using the library for commercial purposes?

**Comment by warpspeed9** [comment]
Andrew,

 

At this point, we are only using the tool we built for our internal customers and not for commercial use. I had switched the program to use the dll library, however, upon having issues at one of our locations with troubleshooting call issues, I’ve since reverted back to using the classes and not referencing the dll.

 

Thanks!

Mike Billiet

(c) 712.490.2881

**Comment by claytondus** [comment]
@NVentimiglia @att14 @warpspeed9 I just created a .NET Standard port from FubarCoder's PCL fork of RestSharp.  It's rough but you can preview it here: https://github.com/claytondus/easypost-csharp

**Comment by Zreitdl** [comment]
@att14  any updates for .net core?

**Comment by whoiskevinrich** [comment]
There is absolutely no reason this can't be turned into a library that targets netstandard, which can then be targeted by both netframework and netcore. Is Easypost open to pull requests? I made a small one for @claytondus's repo, but I'd be happy to come to the source.

**Comment by att14** [comment]
Yes of course.

**Comment by MazdaRacerBoy** [comment]
@att14 Can you merge in Pull Request #108 ?  Thanks.

**Comment by att14** [comment]
Have you verified that #108 works for you. If yes, I'll try to merge it in next time I'm by a Windows computer.

**Comment by MazdaRacerBoy** [comment]
We have been using the branched version in our development environment.  Light usage only, but it appears to be working fine.

**Comment by att14** [comment]
.Net Core is supported, see #122 for information about .Net 4.6.
