### ISSUE TITLE
[Bug]: shipments.all request hangs indefinitely

### ISSUE THREAD

**Issue by klkitchens** [EasyPost/easypost-csharp#503]
### Software Version

5.3.0

### Language Version

.NET 6, C#

### Operating System

Windows 10

### What happened?

1. Create client with credentials.
2. Create parameters object (note this step is optional.  I've created with values, empty parameters, and call All() with no parameter object, all to the same effect.

```
			var parameters = new EasyPost.Parameters.Shipment.All
			{
				//2016-01-02T00:00:00Z
				EndDatetime = $"{toDate:yyyy-MM-dd}",
				StartDatetime = $"{fromDate:yyyy-MM-dd}",
			};
```

3. Call client method:

`			var shipments = _service.Shipment.All(parameters).Result;`

Was not working with 5.1.0 or 5.3.0 nuget packages, so I downloaded the source code to step through natively.  It gets to this line and hangs...  ServiceShipment.cs (line 85)

`            ShipmentCollection collection = await RequestAsync<ShipmentCollection>(Method.Get, "shipments", cancellationToken, parameters.ToDictionary());`

### What was expected?

A collection of Shipments for the dates specified (or all if none specified)

**Comment by nwithan8** [comment]
Hello, thanks for reaching out!

It looks like in Step 3 you're attempting to run the asynchronous function synchronously? Would [this](https://github.com/EasyPost/easypost-csharp/issues/499) be relevant?

**Comment by klkitchens** [comment]
> Hello, thanks for reaching out!
> 
> It looks like in Step 3 you're attempting to run the asynchronous function synchronously? Would [this](https://github.com/EasyPost/easypost-csharp/issues/499) be relevant?

Nope.  C# allows this with the .Result method.  I'm currently running all EasyPost calls this way and they all work fine.  If it's an issue doing so, it's in the EasyPost code for Shipments.All() (or deeper).  I cannot refactor my code to be asynchronous and there is no need to.

Thanks though!

**Comment by klkitchens** [comment]
The workaround/hack found here got passed the problem for shipment.All(), though shipment.Buy() and other calls do not suffer this same problem.

https://gist.github.com/leonardochaia/98ce57bcee39c18d88682424a6ffe305

**Comment by nwithan8** [comment]
What range of dates of shipments were you attempting to retrieve? Perhaps the request was simply too large and was timing out?

**Comment by klkitchens** [comment]
> What range of dates of shipments were you attempting to retrieve? Perhaps the request was simply too large and was timing out?

Nope.  First off it caps at 100.  But I tried just a couple of days of shipments, and limited the page size to 5, etc... nothing.

The hack noted above worked until the bug/design flaw can be fixed.

**Comment by klkitchens** [comment]
OK, so a I spoke too soon.  I went to apply the fix to my other lines of code calling the EasyPost library (in case something changed in the library later) and it turns out I was not doing a direct call with .Result.  My code was structure like this already:

            var shipments = Task.Run<ShipmentCollection>(async () => await _service.Shipment.All(parameters)).Result;
            
So I was already accommodating the need to run the async operations differently, but was juggling several tasks and made the assumption I was calling the others in like fashion.

**My bad.**

But this built in method .NET method prevents the need for the AsyncHelper class.

**Comment by nwithan8** [comment]
Awesome, glad you were able to find a solution that works for you.

Please let us know if anything else comes up!
