### ISSUE TITLE
[Bug]: TimeInTransitDetails.EasyPostEstimatedDeliveryDate has incorrect JSON name mapping

### ISSUE THREAD

**Issue by johnnyh-tactics** [EasyPost/easypost-csharp#505]
### Software Version

5.4

### Language Version

.NET Framework 4.8, Version 10.0.22621 Build 22621

### Operating System

Microsoft Windows 11 Pro

### What happened?

Hi,
This one seems like a straightforward misnaming. I am unable to get the `RateWithEstimatedDeliveryDate.EasyPostTimeInTransitData.EasyPostEstimatedDeliveryDate` value from the results of `Client.Shipment.RetrieveEstimatedDeliveryDate(...)` because the property is defined with the wrong JSON name mapping

```
    [JsonProperty("easypost_time_in_transit_data")]
    public string? EasyPostEstimatedDeliveryDate { get; set; }
```

### What was expected?

Expected the property to be mapped to the JSON name "easypost_estimated_delivery_date" as described in [the example response in the API docs](https://www.easypost.com/docs/api#retrieve-estimated-delivery-date-and-total-transit-days-across-all-rates-for-a-shipment).

### Sample Code

```csharp
[JsonProperty("easypost_estimated_delivery_date")]
public string? EasyPostEstimatedDeliveryDate { get; set; }
```

**Comment by nwithan8** [comment]
Hello, thanks for reaching out!

Good catch on the bug! We'll have a patch out soon and keep you updated!

**Comment by johnnyh-tactics** [comment]
Thanks for the fix! Just tested and all is working for me.
