### ISSUE TITLE
Question regarding the Easy Post API

### ISSUE THREAD

**Issue by eswarvemuri** [EasyPost/easypost-csharp#51]
I was testing out your API. I downloaded the DLL from Nuget Package.

There is some sample code given there.
I tried out the code that gets me Rates for a shipment.
However, I do not see anywhere where there is a call made to the Easy Post Web Service. I think due to this, I am getting Object Reference not set to an instance of object error at the code highlighted in bold.
  foreach (Rate rate in **shipment.rates**)
            {
                RateinDollar = rate.rate;
                // process rates
            }

I also downloaded the C# code from gihub and opened the Project in Visual Studio. Even there I did not see anything under the Service Reference folder. Is there something I am missing? Please let me know

**Comment by att14** [comment]
Looks like there is a missing `Shipment.Create` call. I'll update the docs accordingly.

**Comment by eswarvemuri** [comment]
Thanks. It is working now. I figured that after I posted the question.

I want to ask you another question.

I want to add Carrier information in the Code behind file (.cs) of my C# page.

I went to the Easy Post Portal -> Carrier Accounts and added UPS account and I am able to see UPS rates in my API Call.

However, I do not want to add the Carrier Accounts in Easy Post Portal. I would want to add that from my Code.
However, I did not see any code that tells me how to do it. I can see I have add the Carrier Credentials in a Dictionary Object ( Dictionary<string, object>) But I am not sure what exactly i have to pass.

Can you please let me know if you have any sample code that adds Carrier Credentials from the C# code? That way I can control the rates of various carriers I want to show my Users.

Thanks in advance.

**Comment by att14** [comment]
Yup! We have the ability to do this and it is documented here: https://www.easypost.com/docs/api/c-sharp.html#create-a-carrier-account.

**Comment by eswarvemuri** [comment]
Hi,
The link does not work. Can you please check it?

**Comment by eswarvemuri** [comment]
Hi Andrew,
Here is the link that is broken.

https://www.easypost.com/docs/api/c-sharp.html#create-a-carrier-account

Thanks,
Eswar

**Comment by eswarvemuri** [comment]
Hi Andrew,
I am getting an error at the line CarrierAccount.Create();

The error is –

Severity

Code

Description

Project

File

Line

Error

CS7036

There is no argument given that corresponds to the required formal parameter 'parameters' of 'CarrierAccount.Create(Dictionary<string, object>)'

TestWebApp

C:\Users\Eswar\Documents\Visual Studio 2015\Projects\TestWebApp\TestWebApp\EasyPost.aspx.cs

98



Do I have to create the account (UPS/Fedex) on EasyPost before I access the Rates?

Can I just get the rates from your API with just adding the Carrier Credentials in the request without creating the Credentials in the Easy Post Dashboard?

Thanks,
Eswar

**Comment by att14** [comment]
Sorry about that. Here is the working link: https://www.easypost.com/docs/api/csharp.html#carrier-accounts-create-codesample

**Comment by eswarvemuri** [comment]
Hi Andrew it is pointing to the same code that I saw before.

The issue is with the method ca.Create();  It is the last line in the Create CarrierAccount Example.

**Comment by att14** [comment]
Ah, you are right. Looks like that documentation is wrong. I will update it. You can look at the tests in this library for the correct usage: https://github.com/EasyPost/easypost-csharp/blob/master/EasyPostTest/CarrierAccountTest.cs

**Comment by eswarvemuri** [comment]
Hi,
I have my code modeled according to the link you sent me.

   Dictionary<string, object> credentials = new Dictionary<string, object>() {
  {"account_number", "AccntNo"},
  {"user_id", "UserId"},
  {"password", "Pwd"}

};

            CarrierAccount account = CarrierAccount.Create(new Dictionary<string, object>() {
                {"type", "UPS Account"},
                {"description", "description"},
                {"credentials", credentials }


I get the below error.
Additional information: {"error":{"code":"MODE.UNAUTHORIZED","message":"This resource requires a production API Key to access.","errors":[]}}

I am trying to test the API with the Test API key. If I put the Production API Key, then I need Production Credentials for UPS/Fedex which I do not have.

Thanks,
Eswar

**Comment by eswarvemuri** [comment]
Hi Andrew,
We will ask our Users to create the Carrier Accounts on Easypost Portal. So please ignore my previous Email.

The question I have is, is there a way I can get the Type of Service (Fedex Ground/Priority 2 day, Fedex International etc) when I get the Rates from the Easy Post API? We want to show our users the options(Type of Service) they have when they select a carrier.

Thanks,
Eswar

**Comment by eswarvemuri** [comment]
Adding to my Previous Email what I meant to ask was, For USPS, I can see that in the Rates ,The Service is – “Express” and Delivery Days –“1”. But I do not see where it says “Priority Mail”. Can you let me know where I can get that info?

Thanks,
Eswar

**Comment by att14** [comment]
Each `Rate` has a `service` attribute that will correspond to the carriers service levels. You can also see a full list here: https://www.easypost.com/service-levels-and-parcels.html.

**Comment by eswarvemuri** [comment]
Thanks Andrew. Is there a way to get a list of Service Types without generating the Rates.

I want to show my users the available Service Types before they can select and see the rates.

Also, my program would not know the Weight of the package until User enters it on our website. Does your API have a method that gives us the list of Service Types based on the Carrier selected?

Thanks,
Eswar

**Comment by att14** [comment]
It isn't possible to get a list of service types without weight. If you only want to show service types, just iterate over `Shipment.rates` and grab `Rate.service` from each one.

**Comment by eswarvemuri** [comment]
Hi Andrew,
Another Quick question. Is it possible to get a list of Predefined Packages for Fedex/UPS/USPS from your API?

If so, is it possible to get the dimensions of the Predefined Package too?

We want to show our users a list of Predefined Packages. That way, we do not have to pass the dimensions of the package(which our users may not know) to EasyPost API.

Please let me know.

Thanks,
Eswar

**Comment by att14** [comment]
There isn't a way to do this programmatically currently. We have adding support for this in the backlog, but it isn't prioritized. There is a full list on our website: https://www.easypost.com/service-levels-and-parcels.html

**Comment by chargerback-ron** [comment]
> Ah, you are right. Looks like that documentation is wrong. I will update it. You can look at the tests in this library for the correct usage: https://github.com/EasyPost/easypost-csharp/blob/master/EasyPostTest/CarrierAccountTest.cs

So, **five years** later, the documentation on the site _still_ has not been updated.

**Comment by Justintime50** [comment]
Hey @chargerback-ron, thanks for bringing this back to our attention! I've put up a diff internally to get this corrected on our public facing docs. It's in-review as we speak.

**Comment by chargerback-ron** [comment]
Thank you @Justintime50
