### ISSUE TITLE
[Feat]: Add RestrictionComments to Parameters.CustomsInfo.Create.cs

### ISSUE THREAD

**Issue by chadwixk** [EasyPost/easypost-csharp#597]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

[EasyPost docs](https://docs.easypost.com/docs/customs-infos#customsinfo-object) state `RestrictionComments` are required if `RestrictionType` is not "none".

**Comment by nwithan8** [comment]
Thanks for reaching out!

We are adding the missing property now.
