### ISSUE TITLE
Question: How to set Shipment.Mode?

### ISSUE THREAD

**Issue by chadwixk** [EasyPost/easypost-csharp#599]
This property seems to be in EasyPost.Parameters.Shipment.Create.Options.Mode, but you can't set it. How do you set the shipment mode to Test or Production?

**Comment by nwithan8** [comment]
Most response models have a `Mode` property on them. This cannot/should not be set manually; its value (either `Test` or `Production`) is determined based on which type of API key was used for the API request that created its corresponding object.

**Comment by chadwixk** [comment]
Ah, thanks. We're upgrading from an old version in which you set this. But after I posted, I thought it probably is determined by which API key you used. :)
