### ISSUE TITLE
Event.result does not parse into a ScanForm correctly using LoadFromDictionary

### ISSUE THREAD

**Issue by black-orchid** [EasyPost/easypost-csharp#60]
Perhaps because Event.result in this case mostly has String[] as values instead of strings.

**Comment by att14** [comment]
I am not able to reproduce this. Can you please provide a failing test?

**Comment by black-orchid** [comment]
I noticed after I posted that this is intermittent and can also occur when Event.result is supposed to be a Batch. I'll try to find a pattern.

**Comment by black-orchid** [comment]
In case anyone else runs into it, I'm working around it by getting the id of the object from the dictionary directly and then making a separate Retrieve API call to get the populated object.
