### ISSUE TITLE
Where is EasyPost.pfx?

### ISSUE THREAD

**Issue by tossthekitty** [EasyPost/easypost-csharp#69]
It's not in the package.  

How do I get around this?

**Comment by mwaldt** [comment]
It is a private key used to sign the application. Here is how to develop without it:
Once you have downloaded the repository navigate to the following lines of code and set the value to false:
https://github.com/EasyPost/easypost-csharp/blob/master/EasyPost.Net35/EasyPost.Net35.csproj#L34

https://github.com/EasyPost/easypost-csharp/blob/master/EasyPost.Net40/EasyPost.Net40.csproj#L34
