### ISSUE TITLE
Could not load file or assembly 'RestSharp, Version=100.0.0.0...

### ISSUE THREAD

**Issue by ryn0** [EasyPost/easypost-csharp#70]
When trying to use this package, getting the error: "Could not load file or assembly 'RestSharp, Version=100.0.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

**Comment by att14** [comment]
See #50
