### ISSUE TITLE
EasyPost operations seem to revert System.Net.ServicePointManager.SecurityProtocol to Tls

### ISSUE THREAD

**Issue by MartyIce** [EasyPost/easypost-csharp#75]
We are operating a site that has some integrations that require Tls12, and recently noticed that after invoking a call using easypost-csharp (for example, "address.Create"), our system's SecurityProtocol had been downgraded to Tls.  Looking at your code, I see the following in security.cs:

```
        public static SecurityProtocolType GetProtocol() {
#if NET45
            return SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
#else
            return SecurityProtocolType.Tls;
#endif
        }
    }
```

I couldn't find where this NET45 precompiler flag was getting set, but the version we're using seems to be setting things to "SecurityProtocolType.Tls".  Here's the version we're using:

`  <package id="EasyPost-Official" version="2.2.6" targetFramework="net45" />`

**Comment by att14** [comment]
The `NET45` precompiler flag is set automatically. Can you verify what the return is of `EasyPost.Security.GetProtocol`?

**Comment by MartyIce** [comment]
It returns "Tls":

![image](https://cloud.githubusercontent.com/assets/5083039/23556276/ab45e586-fff1-11e6-832b-79914e7373bd.png)
