### ISSUE TITLE
ScanForm.Create failing

### ISSUE THREAD

**Issue by MartyIce** [EasyPost/easypost-csharp#76]
I'm attempting to use the ScanForm.Create functionality, passing local Shipments (with just their "id" property populated), and am seeing the following error returned:

`{"error":{"code":"SCAN_FORM.CREATE.FAILURE","message":"Unable to create manifest. 2 of the specified shipments were not found: shp_8b44037ea7fb4294a19a3412da786942, shp_195c3f7bfe564d4889769a97e4f52f3e","errors":[]}}`

I have confirmed that both of these shipments exist in our test environment.

**Comment by jmalatia** [comment]
I don't believe you can use `ScanForms` in the test environment.  I believe they are only available in `Production` environment.  At least I seem to remember that to be the case when we were developing our app.

**Comment by MartyIce** [comment]
Are there plans for this in the future?  I can work around it, but it's a rough edge in our consumption of the API.

**Comment by MartyIce** [comment]
I just tested against production environment, and am seeing the same error.

**Comment by mwaldt** [comment]
I am going to close this conversation. I answered this in the support ticket that was also sent in. We have tests built for the scan form object that you can view here:
https://github.com/EasyPost/easypost-csharp/blob/master/EasyPostTest/ScanFormTest.cs
