### ISSUE TITLE
 New issue RestSharp and Newtonsoft JSON references

### ISSUE THREAD

**Issue by justintcgplayer** [EasyPost/easypost-csharp#79]
This is the same issue as #50 which was closed.

When I add the EasyPost-Official package to my project via NuGet, it overwrites my existing Newtonsoft and RestSharp references. Even though RestSharp 105.2.3 is specified as a dependency for EasyPost, it replaces it with RestSharp 100.0.0.0.

**Comment by att14** [comment]
Okay I a reopening #50.
