### ISSUE TITLE
Shipment_Postage_Failure

### ISSUE THREAD

**Issue by awright505** [EasyPost/easypost-csharp#80]
System was working fine for over 6 months but now getting HttpException error when using UPS, SHIPMENT.POSTAGE.FAILURE, "message":"Missing or invalid ship to attention name"

This happens only when an attempted rate is purchased

UK deliveries are fine, it's just international consignments

Regards

Adam Wright FIAP
TWS

**Comment by att14** [comment]
This is a server-side issue that we are currently releasing a fix for. If you continue to have issues please email support@easypost.com

**Comment by awright505** [comment]
Cheers Andrew 

I'll do some testing in the morning, just odd that it's been working great for many months 

Regards


Adam
