### ISSUE TITLE
Accessing request/response json for logging

### ISSUE THREAD

**Issue by dmcclean** [EasyPost/easypost-csharp#9]
It would be nice to have access to the request and response JSON for logging purposes.

I'm not sure exactly how to go about that in a simple way from the existing design, though, since the methods all create the requests, pass them to client, and interpret the responses. You'd sort of need to CQRS-ify it so that there are variants of the methods that just create the response and return it, leaving the programmer responsible for handing it to the client if they actually want it to execute. And once you do that you realize that you probably want the type parameter to be on `Request<T>` in addition to the type parameter dangling off the `Execute<T>(Request ...)` method, so that you could have `Execute<T>(Request<T> ... )`. And it doesn't play 100% nicely with the Merge approach since weird things would happen if you executed the same request twice, but you could just make that case be an exception.

Plus I'm not sure how to get RestSharp to cough up this information either, for similar reasons.

There's got to be a simpler way. I'd almost think about introducing an HTTP proxy and scraping it from there. `RestClient` does support using an `IWebProxy`...

**Comment by miguelhughes** [comment]
From what I could infer from code, easypost uses RestSharp to send requests. There's a [post on SO](https://stackoverflow.com/questions/15683858/restsharp-print-raw-request-and-response-headers) that examines how to enable logging on restsharp, and the hands off approach is to enable net tracing. On net core this is not an option. I resorted to using Telerik's Fiddler, which gave me what I needed.
