### ISSUE TITLE
VB.net usage for address object

### ISSUE THREAD

**Issue by dolphinsd** [EasyPost/easypost-csharp#97]
Since VB.net is case insensitive validate property and Validate methods are in conflict when used on Address object!

**Comment by tig4647** [comment]
I have same issue where verify and validate are ambiguous.

**Comment by att14** [comment]
@dolphinsd can you send me the code that you are speaking of? What version are you running. I don't see anything called validate in the Address object.

**Comment by tig4647** [comment]
Verify is ambiguous in vb.net
there are 2 signatures. One is new in the address object and one is the function
